spring.application.name=presence-service

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8082

# ===============================
# RABBITMQ CONFIGURATION
# ===============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}

# ===============================
# APP RABBITMQ CONFIGURATION
# ===============================
app.rabbitmq.presence-queue=presence-service

# ===============================
# APP MEASUREMENTS CONFIGURATION
# ===============================
app.measurements.radar-presence.name=radarPresence
app.measurements.pir-sensor-presence.name=pirSensorPresence
app.measurements.lamp-state.name=lampState

# ===============================
# GRPC CONFIGURATION
# ===============================
spring.grpc.client.channels.yandex-service.address=yandex-service:9090