spring:
  application:
    name: presence-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  grpc:
    client:
      channels:
        yandex-service:
          address: yandex-service:9090

server:
  port: 8082

app:
  rabbitmq:
    presence-data-queue: presence-data
  grpc:
    lamp-deadline: 8s
  measurements:
    radar-presence:
      name: radarPresence
    pir-sensor-presence:
      name: pirSensorPresence
    lamp-state:
      name: lampState

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
