build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:
  stage: test
  script:
    - echo "This job tests something"

deploy:
  stage: deploy
  variables:
    RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER_UI
    RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS_UI
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch"
    - echo "CI_PROJECT_DIR = $CI_PROJECT_DIR"
    - echo "TEST"
    - docker compose -f docker/docker-compose.yml down
    - docker compose -f docker/docker-compose.yml up -d


