spring:
  application:
    name: api-gateway
  mongodb:
    uri: mongodb://${GATEWAY_MONGO_USER}:${GATEWAY_MONGO_PASS}@mongodb:27017/auth?serverSelectionTimeoutMS=3000&connectTimeoutMS=3000&socketTimeoutMS=5000
  data:
    mongodb:
      auto-index-creation: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: devices
              uri: http://event-service:8081
              predicates:
                - Path=/api/v1/devices/**
            - id: sensor-data
              uri: http://event-service:8081
              predicates:
                - Path=/api/v1/sensor-data/**
            - id: lamp
              uri: http://presence-service:8082
              predicates:
                - Path=/api/v1/lamp/**

server:
  port: 8080

app:
  security:
    jwt-secret: ${JWT_SECRET}
    access-ttl: 15m
  init:
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}