spring.application.name=yandex-service

# ===============================
# YANDEX API CONFIGURATION
# ===============================
yandex.oauth-token=${YANDEX_OAUTH_TOKEN}
yandex.base-url=https://api.iot.yandex.net
yandex.group-action-path=/v1.0/groups/{group_id}/actions
yandex.chandelier-id=${YANDEX_CHANDELIER_ID}
