spring.application.name=event-service

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8081

# ===============================
# RABBITMQ CONFIGURATION
# ===============================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}

# ===============================
# MONGODB CONFIGURATION
# ===============================
spring.data.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/events?authSource=admin

# ===============================
# APP RABBITMQ CONFIGURATION
# ===============================
app.rabbitmq.event-queue=event-service
app.rabbitmq.esp01.availability-queue=esp-01-availability
app.rabbitmq.nodemcu.availability-queue=nodemcu-availability
# IMPORTANT: This value must also be updated in the Arduino sketch
app.rabbitmq.service-availability-queue=event-service-availability

# ===============================
# APP HOME ASSISTANT CONFIGURATION
# ===============================
app.ha.service-availability-topic=homeassistant/event-service/availability
app.ha.esp01.availability-topic=homeassistant/sensor/esp01/availability
app.ha.esp01.state-topic=homeassistant/sensor/esp01/state
app.ha.esp01.discovery-temp-topic=homeassistant/sensor/esp01_temp/config
app.ha.esp01.discovery-hum-topic=homeassistant/sensor/esp01_hum/config
app.ha.nodemcu.availability-topic=homeassistant/sensor/nodemcu/availability
app.ha.nodemcu.state-topic=homeassistant/sensor/nodemcu/state
app.ha.nodemcu.discovery-presence-topic=homeassistant/binary_sensor/nodemcu_presence/config
app.ha.status-topic=homeassistant/status
app.ha.expire-after=60

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.dev.iot.eventservice=DEBUG
